<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<section xmlns="http://docbook.org/ns/docbook" version="5.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:id="_class_assert_exception" xml:lang="en-US">
<title>AssertException Class Reference</title>
<indexterm><primary>AssertException</primary></indexterm>
<para>
<computeroutput>#include &lt;unittest.h&gt;</computeroutput>
</para>
<para>Inheritance diagram for AssertException:    <informalfigure>
        <mediaobject>
            <imageobject>
                <imagedata width="50%" align="center" valign="middle" scalefit="0" fileref="class_assert_exception.png"></imagedata>
            </imageobject>
        </mediaobject>
    </informalfigure>
</para>
<simplesect>
    <title>Public Member Functions    </title>
        <itemizedlist>
            <listitem><para><link linkend="_class_assert_exception_1ac95b6779576904bf5932c1f7e72300c6">AssertException</link> (const char *w)</para>
</listitem>
            <listitem><para><link linkend="_class_assert_exception_1a1a5812bbbb81bd04d4352e3413a5946f">AssertException</link> (const <link linkend="_class_assert_exception">AssertException</link> &amp;rhs)</para>
</listitem>
            <listitem><para>virtual <link linkend="_class_assert_exception_1aba869a44de1c69d593d16d39039bd35c">~AssertException</link> ()  throw ()</para>
</listitem>
        </itemizedlist>
</simplesect>
<section>
<title>Constructor &amp; Destructor Documentation</title>
<anchor xml:id="_class_assert_exception_1ac95b6779576904bf5932c1f7e72300c6"/><section>
    <title>AssertException()<computeroutput>[1/2]</computeroutput></title>
<indexterm><primary>AssertException</primary><secondary>AssertException</secondary></indexterm>
<indexterm><primary>AssertException</primary><secondary>AssertException</secondary></indexterm>
<para><computeroutput>AssertException::AssertException (const char * w)<computeroutput>[inline]</computeroutput></computeroutput></para></section>
<anchor xml:id="_class_assert_exception_1a1a5812bbbb81bd04d4352e3413a5946f"/><section>
    <title>AssertException()<computeroutput>[2/2]</computeroutput></title>
<indexterm><primary>AssertException</primary><secondary>AssertException</secondary></indexterm>
<indexterm><primary>AssertException</primary><secondary>AssertException</secondary></indexterm>
<para><computeroutput>AssertException::AssertException (const <link linkend="_class_assert_exception">AssertException</link> &amp; rhs)<computeroutput>[inline]</computeroutput></computeroutput></para></section>
<anchor xml:id="_class_assert_exception_1aba869a44de1c69d593d16d39039bd35c"/><section>
    <title>~AssertException()</title>
<indexterm><primary>~AssertException</primary><secondary>AssertException</secondary></indexterm>
<indexterm><primary>AssertException</primary><secondary>~AssertException</secondary></indexterm>
<para><computeroutput>AssertException::~AssertException ( ) throw ( ) <computeroutput>[virtual]</computeroutput></computeroutput></para></section>
<para>
The documentation for this class was generated from the following files:</para>
src/rapidjson/test/unittest/<link linkend="_unittest_8h">unittest.h</link>src/rapidjson/test/unittest/<link linkend="_unittest_8cpp">unittest.cpp</link></section>
</section>
